// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "syncNoteIds": string;
      "syncPeriodSeconds": number;
      "syncAttachmentFolder": string;
      "obsidian.appPath": string;
      "obsidian.vaultRoot": string;
      "obsidian.notesDir": string;
      "obsidian.assetsDir": string;
      "obsidian.vaultName": string;
      "obsidian.dashboardDir": string;
      "obsidian.dashboardAutoSetup": boolean;
      "obsidian.setupWizardShown": boolean;
      "obsidian.itemTemplate": string;
      "obsidian.fileNameTemplate": string;
      "obsidian.syncScope": string;
      "obsidian.updateStrategy": string;
      "obsidian.frontmatterFields": string;
      "obsidian.autoSync": boolean;
      "obsidian.watchFiles": boolean;
      "obsidian.revealAfterSync": boolean;
      "obsidian.openAfterSync": boolean;
      "syncHistoryIds": string;
      "obsidian.includeMetadata": boolean;
      "obsidian.includeAbstract": boolean;
      "obsidian.includeHiddenInfo": boolean;
      "obsidian.includeAnnotations": boolean;
      "obsidian.includeChildNotes": boolean;
      "obsidian.metadataPreset": string;
      "obsidian.metadataPresetLibrary": string;
      "obsidian.metadataPresetActive": string;
      "obsidian.itemNoteMap": string;
      "obsidian.bridgeChildNoteTags": string;
      "obsidian.bridgeChildNotePromptSelect": boolean;
      "obsidian.bridgeChildNoteExcludeMap": string;
      "autoAnnotation": boolean;
      "insertLinkPosition": string;
      "workspace.outline.expandLevel": number;
      "workspace.outline.keepLinks": boolean;
      "editor.noteLinkPreviewType": string;
      "editor.useMagicKey": boolean;
      "editor.useMagicKeyShortcut": boolean;
      "editor.useMarkdownPaste": boolean;
      "editor.pinTableLeft": boolean;
      "editor.pinTableTop": boolean;
      "exportNotes.takeover": boolean;
      "annotationNote.enableTagSync": boolean;
    };
  }
}
