"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getScalarJSONValue = exports.formatAbstractLines = exports.getDateYear = exports.escapeTableValue = exports.yamlListBlock = exports.isPlainObject = exports.yamlQuote = exports.stableJSONStringify = exports.normalizeStableValue = exports.normalizeMarkdown = exports.cleanInline = exports.firstValue = exports.hasFrontmatterKey = exports.updateExtraField = exports.parseExtraMap = exports.getFieldSafe = exports.XHTML_NS = exports.findExistingObsidianNote = exports.applyManagedFileNameTemplate = exports.buildManagedFileNameTemplateContext = exports.ensureMarkdownExtension = exports.sanitizeFileNameToken = exports.sanitizeFileNamePart = exports.getVaultRelativeFolder = exports.escapeForDoubleQuotedString = exports.getBestAttachmentLink = exports.makeLibraryLink = exports.getBestItemLink = exports.getItemCollections = exports.buildCollectionItemSelectURI = exports.makeLibraryOpenLink = exports.makeLibrarySelectLink = exports.getLastPathSegment = exports.openObsidianNote = exports.buildObsidianOpenURI = exports.getAttachmentRelativeDir = exports.looksLikeAbsolutePath = exports.getRelativePath = exports.isSamePathSegment = exports.splitComparablePath = exports.getDefaultDashboardDir = void 0;
__exportStar(require("./settings"), exports);
__exportStar(require("./frontmatter"), exports);
__exportStar(require("./markdown"), exports);
__exportStar(require("./childNotes"), exports);
var paths_1 = require("./paths");
Object.defineProperty(exports, "getDefaultDashboardDir", { enumerable: true, get: function () { return paths_1.getDefaultDashboardDir; } });
Object.defineProperty(exports, "splitComparablePath", { enumerable: true, get: function () { return paths_1.splitComparablePath; } });
Object.defineProperty(exports, "isSamePathSegment", { enumerable: true, get: function () { return paths_1.isSamePathSegment; } });
Object.defineProperty(exports, "getRelativePath", { enumerable: true, get: function () { return paths_1.getRelativePath; } });
Object.defineProperty(exports, "looksLikeAbsolutePath", { enumerable: true, get: function () { return paths_1.looksLikeAbsolutePath; } });
Object.defineProperty(exports, "getAttachmentRelativeDir", { enumerable: true, get: function () { return paths_1.getAttachmentRelativeDir; } });
Object.defineProperty(exports, "buildObsidianOpenURI", { enumerable: true, get: function () { return paths_1.buildObsidianOpenURI; } });
Object.defineProperty(exports, "openObsidianNote", { enumerable: true, get: function () { return paths_1.openObsidianNote; } });
Object.defineProperty(exports, "getLastPathSegment", { enumerable: true, get: function () { return paths_1.getLastPathSegment; } });
Object.defineProperty(exports, "makeLibrarySelectLink", { enumerable: true, get: function () { return paths_1.makeLibrarySelectLink; } });
Object.defineProperty(exports, "makeLibraryOpenLink", { enumerable: true, get: function () { return paths_1.makeLibraryOpenLink; } });
Object.defineProperty(exports, "buildCollectionItemSelectURI", { enumerable: true, get: function () { return paths_1.buildCollectionItemSelectURI; } });
Object.defineProperty(exports, "getItemCollections", { enumerable: true, get: function () { return paths_1.getItemCollections; } });
Object.defineProperty(exports, "getBestItemLink", { enumerable: true, get: function () { return paths_1.getBestItemLink; } });
Object.defineProperty(exports, "makeLibraryLink", { enumerable: true, get: function () { return paths_1.makeLibraryLink; } });
Object.defineProperty(exports, "getBestAttachmentLink", { enumerable: true, get: function () { return paths_1.getBestAttachmentLink; } });
Object.defineProperty(exports, "escapeForDoubleQuotedString", { enumerable: true, get: function () { return paths_1.escapeForDoubleQuotedString; } });
Object.defineProperty(exports, "getVaultRelativeFolder", { enumerable: true, get: function () { return paths_1.getVaultRelativeFolder; } });
Object.defineProperty(exports, "sanitizeFileNamePart", { enumerable: true, get: function () { return paths_1.sanitizeFileNamePart; } });
Object.defineProperty(exports, "sanitizeFileNameToken", { enumerable: true, get: function () { return paths_1.sanitizeFileNameToken; } });
Object.defineProperty(exports, "ensureMarkdownExtension", { enumerable: true, get: function () { return paths_1.ensureMarkdownExtension; } });
Object.defineProperty(exports, "buildManagedFileNameTemplateContext", { enumerable: true, get: function () { return paths_1.buildManagedFileNameTemplateContext; } });
Object.defineProperty(exports, "applyManagedFileNameTemplate", { enumerable: true, get: function () { return paths_1.applyManagedFileNameTemplate; } });
Object.defineProperty(exports, "findExistingObsidianNote", { enumerable: true, get: function () { return paths_1.findExistingObsidianNote; } });
var shared_1 = require("./shared");
Object.defineProperty(exports, "XHTML_NS", { enumerable: true, get: function () { return shared_1.XHTML_NS; } });
Object.defineProperty(exports, "getFieldSafe", { enumerable: true, get: function () { return shared_1.getFieldSafe; } });
Object.defineProperty(exports, "parseExtraMap", { enumerable: true, get: function () { return shared_1.parseExtraMap; } });
Object.defineProperty(exports, "updateExtraField", { enumerable: true, get: function () { return shared_1.updateExtraField; } });
Object.defineProperty(exports, "hasFrontmatterKey", { enumerable: true, get: function () { return shared_1.hasFrontmatterKey; } });
Object.defineProperty(exports, "firstValue", { enumerable: true, get: function () { return shared_1.firstValue; } });
Object.defineProperty(exports, "cleanInline", { enumerable: true, get: function () { return shared_1.cleanInline; } });
Object.defineProperty(exports, "normalizeMarkdown", { enumerable: true, get: function () { return shared_1.normalizeMarkdown; } });
Object.defineProperty(exports, "normalizeStableValue", { enumerable: true, get: function () { return shared_1.normalizeStableValue; } });
Object.defineProperty(exports, "stableJSONStringify", { enumerable: true, get: function () { return shared_1.stableJSONStringify; } });
Object.defineProperty(exports, "yamlQuote", { enumerable: true, get: function () { return shared_1.yamlQuote; } });
Object.defineProperty(exports, "isPlainObject", { enumerable: true, get: function () { return shared_1.isPlainObject; } });
Object.defineProperty(exports, "yamlListBlock", { enumerable: true, get: function () { return shared_1.yamlListBlock; } });
Object.defineProperty(exports, "escapeTableValue", { enumerable: true, get: function () { return shared_1.escapeTableValue; } });
Object.defineProperty(exports, "getDateYear", { enumerable: true, get: function () { return shared_1.getDateYear; } });
Object.defineProperty(exports, "formatAbstractLines", { enumerable: true, get: function () { return shared_1.formatAbstractLines; } });
Object.defineProperty(exports, "getScalarJSONValue", { enumerable: true, get: function () { return shared_1.getScalarJSONValue; } });
