// ── Obsidian Prefs UI — Element IDs ──
// All DOM element IDs used in the preferences panel.

import { config } from "../../../../../package.json";

export const OBSIDIAN_SETTINGS_ROOT_ID = `${config.addonRef}-obsidian-settingsRoot`;
export const OBSIDIAN_SETTINGS_STYLE_ID = `${config.addonRef}-obsidian-settingsStyle`;
export const OBSIDIAN_TOOLTIP_ID = `${config.addonRef}-obsidian-tooltip`;
export const OBSIDIAN_APP_PATH_INPUT_ID = `${config.addonRef}-obsidian-appPath`;
export const OBSIDIAN_VAULT_ROOT_INPUT_ID = `${config.addonRef}-obsidian-vaultRoot`;
export const OBSIDIAN_NOTES_DIR_INPUT_ID = `${config.addonRef}-obsidian-notesDir`;
export const OBSIDIAN_ASSETS_DIR_INPUT_ID = `${config.addonRef}-obsidian-assetsDir`;
export const OBSIDIAN_AUTO_SYNC_INPUT_ID = `${config.addonRef}-obsidian-autoSync`;
export const OBSIDIAN_WATCH_FILES_INPUT_ID = `${config.addonRef}-obsidian-watchFiles`;
export const OBSIDIAN_REVEAL_AFTER_SYNC_INPUT_ID = `${config.addonRef}-obsidian-revealAfterSync`;
export const OBSIDIAN_OPEN_AFTER_SYNC_INPUT_ID = `${config.addonRef}-obsidian-openAfterSync`;
export const OBSIDIAN_CONNECTION_STATUS_ID = `${config.addonRef}-obsidian-connectionStatus`;
export const OBSIDIAN_CONNECTION_TEST_BUTTON_ID = `${config.addonRef}-obsidian-connectionTestButton`;
export const OBSIDIAN_CONNECTION_TEST_RESULT_ID = `${config.addonRef}-obsidian-connectionTestResult`;
export const OBSIDIAN_VAULT_ROOT_HINT_ID = `${config.addonRef}-obsidian-vaultRootHint`;
export const OBSIDIAN_NOTES_DIR_HINT_ID = `${config.addonRef}-obsidian-notesDirHint`;
export const OBSIDIAN_ASSETS_DIR_HINT_ID = `${config.addonRef}-obsidian-assetsDirHint`;
export const OBSIDIAN_DASHBOARD_DIR_HINT_ID = `${config.addonRef}-obsidian-dashboardDirHint`;
export const OBSIDIAN_FILE_NAME_RULE_ID = `${config.addonRef}-obsidian-fileNameRule`;
export const OBSIDIAN_FILE_NAME_PREVIEW_ID = `${config.addonRef}-obsidian-fileNamePreview`;
export const OBSIDIAN_FILE_NAME_CONTEXT_ID = `${config.addonRef}-obsidian-fileNameContext`;
export const OBSIDIAN_PREVIEW_TRIGGER_ID = `${config.addonRef}-obsidian-previewTrigger`;
export const OBSIDIAN_PREVIEW_META_ID = `${config.addonRef}-obsidian-previewMeta`;
export const OBSIDIAN_PREVIEW_FILE_ID = `${config.addonRef}-obsidian-previewFile`;
export const OBSIDIAN_PREVIEW_FRONTMATTER_ID = `${config.addonRef}-obsidian-previewFrontmatter`;
export const OBSIDIAN_PREVIEW_BODY_ID = `${config.addonRef}-obsidian-previewBody`;
export const OBSIDIAN_SYNC_SUMMARY_ID = `${config.addonRef}-obsidian-syncSummary`;
export const OBSIDIAN_CONTENT_SUMMARY_ID = `${config.addonRef}-obsidian-contentSummary`;
export const OBSIDIAN_UPDATE_STRATEGY_GROUP_NAME = `${config.addonRef}-obsidian-updateStrategy`;
export const OBSIDIAN_SYNC_SCOPE_GROUP_NAME = `${config.addonRef}-obsidian-syncScopeChoice`;
export const OBSIDIAN_WORKFLOW_EXPORT_NOTES_INPUT_ID = `${config.addonRef}-obsidian-workflow-exportNotes`;
export const OBSIDIAN_WORKFLOW_EXPAND_LEVEL_INPUT_ID = `${config.addonRef}-obsidian-workflow-expandLevel`;
export const OBSIDIAN_WORKFLOW_KEEP_LINKS_INPUT_ID = `${config.addonRef}-obsidian-workflow-keepLinks`;
export const OBSIDIAN_WORKFLOW_NOTE_LINK_PREVIEW_GROUP_NAME = `${config.addonRef}-obsidian-workflow-noteLinkPreview`;
export const OBSIDIAN_WORKFLOW_NOTE_LINK_PREVIEW_HOVER_INPUT_ID = `${config.addonRef}-obsidian-workflow-noteLinkPreview-hover`;
export const OBSIDIAN_WORKFLOW_NOTE_LINK_PREVIEW_CTRL_INPUT_ID = `${config.addonRef}-obsidian-workflow-noteLinkPreview-ctrl`;
export const OBSIDIAN_WORKFLOW_NOTE_LINK_PREVIEW_DISABLE_INPUT_ID = `${config.addonRef}-obsidian-workflow-noteLinkPreview-disable`;
export const OBSIDIAN_WORKFLOW_MAGIC_KEY_INPUT_ID = `${config.addonRef}-obsidian-workflow-magicKey`;
export const OBSIDIAN_WORKFLOW_MAGIC_KEY_SHORTCUT_INPUT_ID = `${config.addonRef}-obsidian-workflow-magicKeyShortcut`;
export const OBSIDIAN_WORKFLOW_MARKDOWN_PASTE_INPUT_ID = `${config.addonRef}-obsidian-workflow-markdownPaste`;
export const OBSIDIAN_WORKFLOW_PIN_LEFT_INPUT_ID = `${config.addonRef}-obsidian-workflow-pinLeft`;
export const OBSIDIAN_WORKFLOW_PIN_TOP_INPUT_ID = `${config.addonRef}-obsidian-workflow-pinTop`;
export const OBSIDIAN_WORKFLOW_SYNC_PERIOD_INPUT_ID = `${config.addonRef}-obsidian-workflow-syncPeriod`;
export const OBSIDIAN_WORKFLOW_ATTACHMENT_FOLDER_INPUT_ID = `${config.addonRef}-obsidian-workflow-attachmentFolder`;
export const OBSIDIAN_WORKFLOW_ANNOTATION_TAG_SYNC_INPUT_ID = `${config.addonRef}-obsidian-workflow-annotationTagSync`;
